version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27777:27017"
    volumes:
      - ./mongo/data:/data/db
  mongo-seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./seed-data:/seed-data
    command:
      'bash -c "mongoimport --host mongodb --db eventdb --collection user  --type json --file /seed-data/users.json --jsonArray && 
                mongoimport --host mongodb --db eventdb --collection event --type json --file /seed-data/events.json --jsonArray"'
